-- COVID-19 DATA ANALYSIS



-- Looking at total cases vs deaths

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, ROUND((TOTAL_DEATHS/TOTAL_CASES)*100,2) AS DEATH_RATIO
FROM DEATHS
WHERE LOCATION ='Colombia'
ORDER BY 1,2

-- Looking at total cases vs population

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION, ROUND((TOTAL_CASES/POPULATION)*100,2) AS INFECTED_RATIO
FROM DEATHS
WHERE LOCATION ='Colombia'
ORDER BY 1,2


-- Countries with highest infection rates

SELECT LOCATION, MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT, POPULATION, MAX((TOTAL_CASES/POPULATION)*100) AS INFECTED_RATIO
FROM DEATHS
GROUP BY 1,3
HAVING MAX((TOTAL_CASES/POPULATION)*100) IS NOT NULL
ORDER BY 4 DESC;