-- COVID-19 DATA ANALYSIS



-- Looking at total cases vs deaths

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, ROUND((TOTAL_DEATHS/TOTAL_CASES)*100,2) AS DEATH_RATIO
FROM DEATHS
WHERE LOCATION ='Colombia'
ORDER BY 1,2

-- Looking at total cases vs population

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION, ROUND((TOTAL_CASES/POPULATION)*100,2) AS INFECTED_RATIO
FROM DEATHS
WHERE LOCATION ='Colombia'
ORDER BY 1,2
